// Code generated by protoc-gen-go. DO NOT EDIT.
// source: InitConnect.proto

package InitConnect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S struct {
	ClientVer  *int32  `protobuf:"varint,1,req,name=clientVer" json:"clientVer,omitempty"`
	ClientID   *string `protobuf:"bytes,2,req,name=clientID" json:"clientID,omitempty"`
	RecvNotify *bool   `protobuf:"varint,3,opt,name=recvNotify" json:"recvNotify,omitempty"`
	//如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
	//如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
	PacketEncAlgo        *int32   `protobuf:"varint,4,opt,name=packetEncAlgo" json:"packetEncAlgo,omitempty"`
	PushProtoFmt         *int32   `protobuf:"varint,5,opt,name=pushProtoFmt" json:"pushProtoFmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e68d7dcc5c46c8, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetClientVer() int32 {
	if m != nil && m.ClientVer != nil {
		return *m.ClientVer
	}
	return 0
}

func (m *C2S) GetClientID() string {
	if m != nil && m.ClientID != nil {
		return *m.ClientID
	}
	return ""
}

func (m *C2S) GetRecvNotify() bool {
	if m != nil && m.RecvNotify != nil {
		return *m.RecvNotify
	}
	return false
}

func (m *C2S) GetPacketEncAlgo() int32 {
	if m != nil && m.PacketEncAlgo != nil {
		return *m.PacketEncAlgo
	}
	return 0
}

func (m *C2S) GetPushProtoFmt() int32 {
	if m != nil && m.PushProtoFmt != nil {
		return *m.PushProtoFmt
	}
	return 0
}

type S2C struct {
	ServerVer            *int32   `protobuf:"varint,1,req,name=serverVer" json:"serverVer,omitempty"`
	LoginUserID          *uint64  `protobuf:"varint,2,req,name=loginUserID" json:"loginUserID,omitempty"`
	ConnID               *uint64  `protobuf:"varint,3,req,name=connID" json:"connID,omitempty"`
	ConnAESKey           *string  `protobuf:"bytes,4,req,name=connAESKey" json:"connAESKey,omitempty"`
	KeepAliveInterval    *int32   `protobuf:"varint,5,req,name=keepAliveInterval" json:"keepAliveInterval,omitempty"`
	AesCBCiv             *string  `protobuf:"bytes,6,opt,name=aesCBCiv" json:"aesCBCiv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e68d7dcc5c46c8, []int{1}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetServerVer() int32 {
	if m != nil && m.ServerVer != nil {
		return *m.ServerVer
	}
	return 0
}

func (m *S2C) GetLoginUserID() uint64 {
	if m != nil && m.LoginUserID != nil {
		return *m.LoginUserID
	}
	return 0
}

func (m *S2C) GetConnID() uint64 {
	if m != nil && m.ConnID != nil {
		return *m.ConnID
	}
	return 0
}

func (m *S2C) GetConnAESKey() string {
	if m != nil && m.ConnAESKey != nil {
		return *m.ConnAESKey
	}
	return ""
}

func (m *S2C) GetKeepAliveInterval() int32 {
	if m != nil && m.KeepAliveInterval != nil {
		return *m.KeepAliveInterval
	}
	return 0
}

func (m *S2C) GetAesCBCiv() string {
	if m != nil && m.AesCBCiv != nil {
		return *m.AesCBCiv
	}
	return ""
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e68d7dcc5c46c8, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e68d7dcc5c46c8, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "InitConnect.C2S")
	proto.RegisterType((*S2C)(nil), "InitConnect.S2C")
	proto.RegisterType((*Request)(nil), "InitConnect.Request")
	proto.RegisterType((*Response)(nil), "InitConnect.Response")
}

func init() {
	proto.RegisterFile("InitConnect.proto", fileDescriptor_70e68d7dcc5c46c8)
}

var fileDescriptor_70e68d7dcc5c46c8 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x6f, 0xd4, 0x30,
	0x10, 0x85, 0x95, 0xcd, 0xa6, 0xbb, 0x9d, 0x2d, 0x12, 0x35, 0x02, 0x59, 0x15, 0xaa, 0xa2, 0x88,
	0x43, 0x0e, 0x34, 0xaa, 0x22, 0x4e, 0xdc, 0xb6, 0x6e, 0x91, 0x22, 0x04, 0x42, 0x0e, 0x70, 0x0f,
	0x66, 0xba, 0x44, 0x4d, 0x6c, 0x63, 0x3b, 0x91, 0xf6, 0xc6, 0xdf, 0xe1, 0x97, 0xf0, 0xb7, 0x90,
	0xbd, 0xbb, 0x25, 0xa5, 0x37, 0xbf, 0xef, 0x59, 0x9a, 0xf7, 0x66, 0xe0, 0xb4, 0x92, 0xad, 0x63,
	0x4a, 0x4a, 0x14, 0xae, 0xd0, 0x46, 0x39, 0x45, 0x56, 0x13, 0x74, 0x76, 0xc2, 0x54, 0xdf, 0x2b,
	0xb9, 0xb3, 0xb2, 0xdf, 0x11, 0xc4, 0xac, 0xac, 0xc9, 0x4b, 0x38, 0x16, 0x5d, 0x8b, 0xd2, 0x7d,
	0x45, 0x43, 0xa3, 0x74, 0x96, 0x27, 0xfc, 0x1f, 0x20, 0x67, 0xb0, 0xdc, 0x89, 0xea, 0x9a, 0xce,
	0xd2, 0x59, 0x7e, 0xcc, 0xef, 0x35, 0x39, 0x07, 0x30, 0x28, 0xc6, 0x8f, 0xca, 0xb5, 0xb7, 0x5b,
	0x1a, 0xa7, 0x51, 0xbe, 0xe4, 0x13, 0x42, 0x5e, 0xc1, 0x13, 0xdd, 0x88, 0x3b, 0x74, 0x37, 0x52,
	0xac, 0xbb, 0x8d, 0xa2, 0xf3, 0x34, 0xca, 0x13, 0xfe, 0x10, 0x92, 0x0c, 0x4e, 0xf4, 0x60, 0x7f,
	0x7c, 0xf2, 0xa1, 0xde, 0xf5, 0x8e, 0x26, 0xe1, 0xd3, 0x03, 0x96, 0xfd, 0x89, 0x20, 0xae, 0x4b,
	0xe6, 0xb3, 0x5a, 0x34, 0x23, 0x9a, 0x49, 0xd6, 0x7b, 0x40, 0x52, 0x58, 0x75, 0x6a, 0xd3, 0xca,
	0x2f, 0x16, 0xcd, 0x3e, 0xee, 0x9c, 0x4f, 0x11, 0x79, 0x01, 0x47, 0x42, 0x49, 0x59, 0x5d, 0xd3,
	0x38, 0x98, 0x7b, 0xe5, 0x9b, 0xf8, 0xd7, 0xfa, 0xa6, 0x7e, 0x8f, 0x5b, 0x3a, 0x0f, 0x3d, 0x27,
	0x84, 0xbc, 0x86, 0xd3, 0x3b, 0x44, 0xbd, 0xee, 0xda, 0x11, 0x2b, 0xe9, 0xd0, 0x8c, 0x4d, 0x47,
	0x93, 0x30, 0xff, 0xb1, 0xe1, 0x77, 0xd6, 0xa0, 0x65, 0x57, 0xac, 0x1d, 0xe9, 0x51, 0x1a, 0xf9,
	0x9d, 0x1d, 0x74, 0x76, 0x01, 0x0b, 0x8e, 0x3f, 0x07, 0xb4, 0x8e, 0x64, 0x10, 0x8b, 0xd2, 0x86,
	0x1a, 0xab, 0xf2, 0x69, 0x31, 0x3d, 0x1e, 0x2b, 0x6b, 0xee, 0xcd, 0xec, 0x57, 0x04, 0x4b, 0x8e,
	0x56, 0x2b, 0x69, 0x91, 0x9c, 0xc3, 0xc2, 0xa0, 0xfb, 0xbc, 0xd5, 0xb8, 0xeb, 0xfe, 0x76, 0x7e,
	0xf1, 0xe6, 0xf2, 0x92, 0x1f, 0xa0, 0x6f, 0x67, 0xd0, 0x7d, 0xb0, 0x1b, 0x3a, 0x0b, 0x53, 0xf7,
	0x8a, 0x50, 0x58, 0xa0, 0x31, 0x4c, 0x7d, 0xc7, 0x70, 0xa4, 0x84, 0x1f, 0xa4, 0x8f, 0x60, 0x4b,
	0x11, 0xee, 0xf2, 0x7f, 0x84, 0xba, 0x64, 0xdc, 0x9b, 0x57, 0xcf, 0xe1, 0x99, 0x50, 0x7d, 0x71,
	0x3b, 0xb8, 0xa1, 0x50, 0x1a, 0x65, 0xa3, 0xdb, 0x42, 0x7f, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0x9f, 0xb5, 0xd5, 0x6d, 0x02, 0x00, 0x00,
}
